services:
  btc-monitor:
    container_name: btc-monitor
    build:
      context: .
      dockerfile: Dockerfile
    image: btc-monitor
    volumes:
     - ./src:/app
    working_dir: /app
    command: ["python", "-B", "main.py"]
